version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    environment: 
      - "DATABASE_HOST=db"
    ports:
      # - "4000:4000"
      - "4001:4001"
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /opt/app
  db:
    image: postgis/postgis:16-3.4-alpine
    # ports:
    #   - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
